name: Install MonetDB
description: Install MonetDB and make it ready for use
outputs:
  bindir:
    description: where binaries are installed
    value: ${{ steps.set_output.outputs.bindir }}
  includedir:
    description: where include files are installed
    value: ${{ steps.set_output.outputs.includedir }}
  libdir:
    description: where libraries are installed
    value: ${{ steps.set_output.outputs.libdir }}
  dynsuffix:
    description: "the extension used for shared libraries on this platform: so, dylib or dll"
    value: ${{ steps.set_output.outputs.dynsuffix }}

runs:
  using: "composite"
  steps:

  - name: Linux Package Install
    if: runner.os == 'Linux'
    run: ${{ github.action_path }}/install-linux-bin.sh
    shell: bash

  - name: MacOS Homebrew Install
    if: runner.os == 'macOS'
    run: ${{ github.action_path }}/install-macos-bin.sh
    shell: bash

  - name: Windows MSI Install
    if: runner.os == 'Windows'
    uses: ./install-windows-bin

  - name: Is it still running
    run: python3 ${{ github.action_path }}\tryconnect.py
    shell: pwsh

  - name: Communicate bindir, libdir, includedir and dynsuffix
    id: set_output
    run: |
      cat github.output # should have been generated by install-*-bin.sh
      cat github.output >>$GITHUB_OUTPUT
    shell: bash