name: Install MonetDB
description: Install MonetDB and make it ready for use
inputs:
  version:
    description: "Version of MonetDB to install"
    required: false
    default: Latest
  start:
    description: "Start the server if this is equal to 'true' (the default)"
    required: false
    default: "true"
outputs:
  prefix:
    description: directory prefix under which everything has been installed
    value: ${{ steps.set_output.outputs.prefix }}
  bindir:
    description: directory under $prefix where binaries has been installed
    value: ${{ steps.set_output.outputs.bindir }}
  includedir:
    description: directory under $prefix where include files has been installed
    value: ${{ steps.set_output.outputs.includedir }}
  libdir:
    description: directory under $prefix where libraries has been installed
    value: ${{ steps.set_output.outputs.libdir }}
  dynsuffix:
    description: "the extension used for shared libraries on this platform: so, dylib or dll"
    value: ${{ steps.set_output.outputs.dynsuffix }}
  versionnumber:
    description: "installed version of MonetDB, for example 11.51.5"
    value: ${{ steps.versionlookup.outputs.numeric }}
  dbfarm:
    description:  "location of the started dbfarm (not on Windows)"
    value: ${{ steps.set_output.outputs.dbfarm }}

# input: version
# output: version_number

runs:
  using: "composite"
  steps:

  # this step has outputs 'numeric'
  - id: versionlookup
    run: |
      python3 "$GITHUB_ACTION_PATH"/lookup-version.py "${{ inputs.version }}" ${{ runner.os == 'Windows' && '--msi' || '' }} >"$GITHUB_OUTPUT"
      cat "$GITHUB_OUTPUT"
    shell: bash

  # This step leaves GITHUB_OUTPUT in the file github.output
  - name: Linux Package Install
    if: runner.os == 'Linux'
    run: |
      echo "$GITHUB_ACTION_PATH"
      ls "$GITHUB_ACTION_PATH"
      "$GITHUB_ACTION_PATH"/install-linux-bin.sh "${{ steps.versionlookup.outputs.numeric }}" "${{ inputs.start }}"
    shell: bash

  # This step leaves GITHUB_OUTPUT in the file github.output
  - name: MacOS Homebrew Install
    if: runner.os == 'macOS'
    run: |
      "$GITHUB_ACTION_PATH"/install-macos-bin.sh "${{ steps.versionlookup.outputs.numeric }}" "${{ inputs.start }}"
    shell: bash

  # This step leaves GITHUB_OUTPUT in the file github.output.
  # It also updates $GITHUP_PATH.
  - name: Windows MSI Install
    if: runner.os == 'Windows'
    run: ${{ github.action_path}}\install-windows-bin.ps1 "${{ steps.versionlookup.outputs.main_msi }}" "${{ steps.versionlookup.outputs.odbc_msi }}" "${{ inputs.start }}"
    shell: pwsh

  - name: Check whether the server is really running
    if: inputs.start == true || inputs.start == 'true'
    run: python3 "$GITHUB_ACTION_PATH"/connect-to-socket.py
    shell: bash

  - name: Create .monetdb
    run: |
      echo user=monetdb >> $HOME/.monetdb
      echo password=monetdb >> $HOME/.monetdb
    shell: bash

  - name: Create a scratch venv
    id: venv
    if: inputs.start == true || inputs.start == 'true'
    # The python / python3 conditional is needed on windows-2019 runners
    run: |
      ${{ runner.os == 'Windows' && 'python' || 'python3' }} -m venv "$RUNNER_TEMP"/install-monetdb-venv
      echo "activate=$RUNNER_TEMP/install-monetdb-venv/${{ runner.os == 'Windows' && 'Scripts' || 'bin' }}/activate" >>"$GITHUB_OUTPUT"

    shell: bash

  - name: Verify that the correct version has been installed
    if: inputs.start == true || inputs.start == 'true'
    run: |
      . '${{ steps.venv.outputs.activate }}'
      python -m pip install pymonetdb
      python "$GITHUB_ACTION_PATH"/verify-with-pymonetdb.py monetdb:///demo --expect-version="${{ steps.versionlookup.outputs.numeric }}"
    shell: bash

  # This step picks up the github.output file generated
  # by the earlier install step
  - name: Communicate prefix, bindir, libdir, includedir and dynsuffix
    id: set_output
    run: |
      cat github.output # should have been generated by install-*-bin.sh
      cat github.output >>$GITHUB_OUTPUT
    shell: bash