name: Install Windows Binaries
description: sub-action for installing Windows binaries
inputs:
  main_msi_url:
    description: URL of MonetDB installer
    required: true
  odbc_msi:
    required: true
    description: URL of ODBC installer
  prefix:
    description: Where to install MonetDB (do not change)
    default: C:\Program Files\MonetDB\MonetDB5
    required: false
  odbc_prefix:
    description: Where to install the ODBC driver (do not change)
    default: C:\Program Files\MonetDB\MonetDB ODBC Driver
    required: false

runs:
  using: "composite"
  steps:

  - name: Install MSI files
    run: |
          $main_file="c:\monetdb.msi"
          Write-Output "Download and install '$main_file' from '${{ inputs.main_msi_url }}'"
          (New-Object System.Net.WebClient).DownloadFile("${{ inputs.main_msi_url }}","$main_file");
          Start-Process "$main_file" -ArgumentList '/quiet /passive /qn /norestart INSTALLLEVEL=1000 MSIRMSHUTDOWN=2' -Wait
          #
          $odbc_file="c:\monetdb-odbc.msi"
          Write-Output "Download and install '$odbc_file' from '${{ inputs.odbc_msi_url }}'"
          (New-Object System.Net.WebClient).DownloadFile("${{ inputs.odbc_msi_url }}","$odbc_file");
          Start-Process "$odbc_file" -ArgumentList '/quiet /passive /qn /norestart INSTALLLEVEL=1000 MSIRMSHUTDOWN=2' -Wait
    shell: pwsh

  - name: Make sure embedded Python remains disabled
    run: del "${{ inputs.prefix }}\pyapi_locatepython3.bat"
    shell: cmd

  - name: Set output parameters
    run: |
      Add-Content github.output "prefix=${{ inputs.prefix }}"
      Add-Content github.output "bindir=${{ inputs.prefix }}"
      Add-Content github.output "includedir=${{ inputs.prefix }}/include"
      Add-Content github.output "libdir=${{ inputs.prefix }}\bin"
      Add-Content github.output "dynsuffix=dll"
      cat github.output
    shell: pwsh

  - name: Update PATH
    run: |
      Add-Content $env:GITHUB_PATH "${{ inputs.prefix }}"
    shell: pwsh

  - name: Start the server
    run: |
      $opts = @{
        FilePath = "${{ inputs.prefix }}\MSQLserver.bat"
        #NoNewWindow = $true
        #ArgumentList = "--set","embedded_py=false"
      }
      Start-Process @opts
    shell: pwsh
