name: Test the Install Action
on:
  push:
jobs:

  documentation-example:
    if: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.
      - run: mclient -d demo -s 'SELECT * FROM environment'


  binary:
    if: true
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04        # intel
          - ubuntu-22.04        # intel
          - ubuntu-20.04        # intel
          - macos-13            # intel
          - macos-12            # intel
          - macos-15            # arm
          - macos-14            # arm
          - windows-2022        # intel
          - windows-2019        # intel
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v4

    - name: Run the action
      id: thisaction
      uses: ./.

    - name: Check activity output parameters
      run: |
        ls "${{ steps.thisaction.outputs.prefix }}"
        ls "${{ steps.thisaction.outputs.bindir }}/mclient${{ runner.os == 'Windows' && '.bat' || ''}}"
        ls "${{ steps.thisaction.outputs.includedir }}/monetdbe.h"
        ls "${{ steps.thisaction.outputs.libdir }}/${{ (runner.os != 'Windows' && 'lib') || '' }}monetdbe.${{ steps.thisaction.outputs.dynsuffix }}"

    - name: Test mclient --version
      run: mclient --version

    - name: Try to connect with mclient
      # does not work on Windows yet, don't know why  :( :( :(
      if: runner.os != 'Windows'
      run: mclient -L- -d demo -s 'select * from environment'

    - name: Set up venv for pymonetdb
      run: |
        python3 -m venv venv
        python3 -c 'import os; print(os.path.join(os.getcwd(), "venv", "bin"))' >>$GITHUB_PATH

    - name: Try to connect with pymonetdb
      run: |
        python -m pip install pymonetdb
        python verify-with-pymonetdb.py monetdb:///demo --expect-version="${{ steps.thisaction.outputs.versionnumber }}"
      shell: bash


  binary-withversion:
    if: true
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
    env:
      # Since Aug2024-SP1 (11.51.5) has been release, Aug2024 (11.51.3) is no
      # longer the default version.
      MDB_RELEASE: Aug2024
      EXPECTED_VERSION: 11.51.3
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v4

    - name: Run the action with
      id: thisaction
      uses: ./.
      with:
        version: "${{ env.MDB_RELEASE }}"

    - name: Quick version check
      run: test "x${{ steps.thisaction.outputs.versionnumber }}" = "x${{ env.EXPECTED_VERSION }}"
      shell: bash

    - name: Set up venv for pymonetdb
      run: |
        python3 -m venv venv
        python3 -c 'import os; print(os.path.join(os.getcwd(), "venv", "bin"))' >>$GITHUB_PATH

    - name: Try to connect with pymonetdb
      run: |
        python -m pip install pymonetdb
        python verify-with-pymonetdb.py monetdb:///demo --expect-version="${{ steps.thisaction.outputs.versionnumber }}"
      shell: bash


  source:
    if: false
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest       # intel
          - macos-15            # arm
          - windows-latest      # intel
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:

    - uses: actions/checkout@v4

    - name: Download MonetDB source
      run: |
        release=Aug2024_SP1
        tarfile="$release"_release.tar.gz
        url="https://github.com/MonetDB/MonetDB/archive/refs/tags/$tarfile"
        wget -q "$url" -O "$tarfile"
        ls -l "$tarfile"
        mkdir src
        cd src
        tar zxf ../"$tarfile"
        ls
      shell: bash

      # - name: Run the action
    #   id: thisaction
    #   uses: ./.

    # - name: Check activity output parameters
    #   run: |
    #     ls "${{ steps.thisaction.outputs.prefix }}"
    #     ls "${{ steps.thisaction.outputs.bindir }}/mclient${{ runner.os == 'Windows' && '.bat' || ''}}"
    #     ls "${{ steps.thisaction.outputs.includedir }}/monetdb/monetdbe.h"
    #     ls "${{ steps.thisaction.outputs.libdir }}/libmonetdbe.${{ steps.thisaction.outputs.dynsuffix }}"

    # - name: Test mclient --version
    #   run: mclient --version

    # - name: Try to connect with mclient
    #   # does not work on Windows yet, don't know why  :( :( :(
    #   if: runner.os != 'Windows'
    #   run: mclient -L- -d demo -s 'select * from environment'

    # - name: Set up venv for pymonetdb
    #   run: |
    #     python3 -m venv venv
    #     python3 -c 'import os; print(os.path.join(os.getcwd(), "venv", "bin"))' >>$GITHUB_PATH

    # - name: Try to connect with pymonetdb
    #   run: |
    #     python -m pip install pymonetdb
    #     python verify-with-pymonetdb.py monetdb:///demo --expect-version="${{ steps.thisaction.outputs.versionnumber }}"
    #   shell: bash

