name: Test the Install Action
on:
  push:
jobs:

  documentation-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.
      - run: mclient -d demo -s 'SELECT * FROM environment'


  test-basics:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest       # intel
          - ubuntu-24.04        # intel
          - ubuntu-22.04        # intel
          - ubuntu-20.04        # intel
          - macos-13            # intel
          - macos-12            # intel
          - macos-15            # arm
          - macos-14            # arm
          - windows-latest      # intel
          - windows-2022        # intel
          - windows-2019        # intel
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v4

    - name: Run the action
      id: thisaction
      uses: ./.

    - name: Check activity output parameters
      if: runner.os != 'Windows'
      run: |
        ls "${{ steps.thisaction.outputs.prefix }}"
        ls "${{ steps.thisaction.outputs.bindir }}/mclient"
        ls "${{ steps.thisaction.outputs.includedir }}/monetdb/monetdbe.h"
        ls "${{ steps.thisaction.outputs.libdir }}/libmonetdbe.${{ steps.thisaction.outputs.dynsuffix }}"

    - name: Check activity output parameters
      if: runner.os == 'Windows'
      run: |
        ls "${{ steps.thisaction.outputs.prefix }}"
        ls "${{ steps.thisaction.outputs.bindir }}/mclient.bat"
        ls "${{ steps.thisaction.outputs.includedir }}/monetdb/monetdbe.h"
        ls "${{ steps.thisaction.outputs.libdir }}/monetdbe.${{ steps.thisaction.outputs.dynsuffix }}"

    - name: Test mclient --version
      run: mclient --version

    - name: Try to connect with mclient
      # does not work on Windows yet, don't know why  :( :( :(
      if: runner.os != 'Windows'
      run: mclient -L- -d demo -s 'select * from environment'

    - name: Set up venv for pymonetdb
      run: |
        python3 -m venv venv
        python3 -c 'import os; print(os.path.join(os.getcwd(), "venv", "bin"))' >>$GITHUB_PATH

    - name: Try to connect with pymonetdb
      run: |
        python -m pip install pymonetdb
        python verify-with-pymonetdb.py monetdb:///demo --expect-version="${{ steps.thisaction.outputs.versionnumber }}"
      shell: bash


  test-withversion:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
    env:
      # Since Aug2024-SP1 (11.51.5) has been release, Aug2024 (11.51.3) is no
      # longer the default version.
      MDB_RELEASE: Aug2024
      EXPECTED_VERSION: 11.51.3
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v4

    - name: Run the action with
      id: thisaction
      uses: ./.
      with:
        version: "${{ env.MDB_RELEASE }}"

    - name: Quick version check
      run: test "x${{ steps.thisaction.outputs.versionnumber }}" = "x${{ env.EXPECTED_VERSION }}"
      shell: bash

    - name: Set up venv for pymonetdb
      run: |
        python3 -m venv venv
        python3 -c 'import os; print(os.path.join(os.getcwd(), "venv", "bin"))' >>$GITHUB_PATH

    - name: Try to connect with pymonetdb
      run: |
        python -m pip install pymonetdb
        python verify-with-pymonetdb.py monetdb:///demo --expect-version="${{ steps.thisaction.outputs.versionnumber }}"
      shell: bash